### ISSUE TITLE
Idée - màj statut après exécution d'une action

### ISSUE THREAD

**Issue by smuteau** [redbug26/jeedom-tahoma#1]
Salut redbug,
pour une utilisation "classique", les 15mn de check conviennent parfaitement.
Par contre, est-il possible de faire un update du "volet" après la fin d'exécution d'une action pour récupérer les infos ?
En gros, je descends mon volet du bureau à 16h48, je l'arrête à 64% mais je n'aurai l'info qu'à 17h (cron) alors que j'aimerais avoir l'info de suite (pour coupler avec les conditions d'exécution du plugin Gestion de Volets par exemple).
Merci pour ton plugin !!

**Comment by redbug26** [comment]
Fait à l'instant :)
