### ISSUE TITLE
plugin non fonctionnel

### ISSUE THREAD

**Issue by boniny** [redbug26/jeedom-tahoma#20]
Bonjour
Je viens d'installer jeedom en version 4.0.21 et le plugin Tahoma, la configuration est OK, la synchro aussi, l'accès à distance de la Tahoma est bien activée mais impossible d'utiliser les commande.

Merci de votre aide.

![Capture d’écran 2019-10-11 à 11 31 32](https://user-images.githubusercontent.com/56434073/66641315-c599b300-ec1a-11e9-8b4e-97438a832508.png)
![Capture d’écran 2019-10-11 à 11 33 03](https://user-images.githubusercontent.com/56434073/66641435-0a254e80-ec1b-11e9-96a3-9007b7eb51da.png)

**Comment by SamsGuamejy** [comment]
+1
J'ai le même soucis de fonctionnement. En creusant sur les forums j'ai croisé un problème qui serait lié au PHP7.3.

**Comment by boniny** [comment]
Merci de ton retour, n'hésites pas à communiquer si tu trouves une solution à ce problème.
Merci de ton aide.

**Comment by jandry** [comment]
Bonjour,
Je viens d'installer un jeedom tout frais avec la nouvelle option de la freebox Delta
Du coup c'est un jeedom 4.0.21 et un php 7.3.9-1~deb10u1 
Et j'ai exactement l'erreur et rien dans les logs du plugin

**Comment by boniny** [comment]
Bonjour,
Avez-vous le même souci avec d'autres plugins ? 
J'ai le même souci avec le plugin Monitoring, alors je pense que ça vient plus du core que des plugins.

**Comment by jandry** [comment]
J'ai le même soucis avec un autre plugin sigri_linky. Mais tous les autres fonctionnent

J'ai une installation toute fraîche correspondant à ça
https://jeedom.github.io/documentation/installation/fr_FR/index#tocAnchor-1-9

Donc attendez vous aux mêmes reports dans les semaines à venir vu que c'est tout chaud cette installation freebox

**Comment by redbug26** [comment]
#21

**Comment by boniny** [comment]
Super, merci !

**Comment by jandry** [comment]
nickel #21 fonctionne
