### ISSUE TITLE
No more communication since last tahoma API update

### ISSUE THREAD

**Issue by SlyBall912** [redbug26/jeedom-tahoma#23]
Hi,

Since the last tahoma API update (2019-12-03), the communication from Jeedom plugin and tahoma account is NOK. 

Thanks a lot for your help !

Regards

Sylvain

**Comment by BomberX** [comment]
Hi,

Confirmed: I got the same pb here !
Maybe some APIs changed from Somfy side ?

Again thanks for your support on this great plugin !

Regards

BX

**Comment by ViVaLaWeEd** [comment]
Hi,

Confirmed too: Same problem since the last somfy update.

Thanks for support 

Regards

Alex

**Comment by raphaelpregnon** [comment]
Hi, confirmed too: same problem
Raph

**Comment by redbug26** [comment]
Fixed by @jordan-akki 
Thanks to him
