### ISSUE TITLE
Panel.php introuvable

### ISSUE THREAD

**Issue by bibonade** [redbug26/jeedom-tahoma#26]
Bonjour,
j'utilise la plugin jeedom depuis plus d'un an maintenant, ça fonctionne très bien à une exception près : je n'ai jamais eu accès a la vue "Tahoma" normalement accessible depuis le menu "Accueil" de jeedom. Quand je clique dessus, j'ai un message d'erreur :

`Fichier introuvable : /var/www/html/core/php/../../plugins/tahoma/desktop/php/panel.php`

![Sans titre](https://user-images.githubusercontent.com/22047873/73850915-ecfd3700-482c-11ea-8372-c023e7540284.jpg)

**Comment by redbug26** [comment]
Je n'ai pas cette vue dans ma liste.
Comment l'as tu fait apparaître ?

**Comment by bibonade** [comment]
Je n'ai rien fait de particluler à ma connaissance.
Malheureusement je n'utilise plus jeedom aujourd'hui, je ne pourrais pas te renseigner davantage.
