### ISSUE TITLE
Homebridge Tahoma RTS

### ISSUE THREAD

**Issue by ChrisJary** [redbug26/jeedom-tahoma#3]
Bonjour,

j'ai acheté le plugin pour permettre le contrôle de mes volets et portail SOMFY RTS au travers de ma box tahoma depuis mon iphone avec homebridge.
Cependant homebridge nécessite d'avoir un retour d'état sur le protocole RTS, il y a t-il une astuce pour permettre son bon fonctionnement?
Cordialement.
Christopher Jary

**Comment by redbug26** [comment]
Je n'ai pas de volets en RTS donc je ne peux pas tester.
Deja, la nouvelle version sortie aujourd'hui fonctionnera mieux :)
Mais je pense qu'un virtuel sera necessaire
