### ISSUE TITLE
Etat des commandes info non disponibles dans les commandes actions -issue closes without resolution !

### ISSUE THREAD

**Issue by antarmc** [redbug26/jeedom-tahoma#36]
Hi

Aucun Etat des commandes info n'est disponible dans les commandes actions

Impossible d'actualiser l'etat des equipements/widget etc.

Jeedom 4.1.18

![image](https://user-images.githubusercontent.com/56517380/106503305-bef51600-64c5-11eb-9cea-d542cd6ca406.png)

![image](https://user-images.githubusercontent.com/56517380/106503371-cb796e80-64c5-11eb-9761-aed45a7cb76a.png)

Merci de votre aide

**Comment by redbug26** [comment]
Corrigé dans la mise à jour d'aujourd'hui

**Comment by antarmc** [comment]
Hélas non... 

![image](https://user-images.githubusercontent.com/56517380/155033085-da20d2d8-0ef9-4732-b980-953beca349bd.png)

L’idée ici est en effet d'obtenir un retour de l’état d'ouverture du volet, quelle que soit la source de l'ordre, et qui puisse également être utilisé pour piloter le volet (commande setclosure en mode #slider#) de façon très visuelle, par le biais d'un widget sur cette commande, prenant ainsi l'apparence du volet :   

![image](https://user-images.githubusercontent.com/56517380/155033290-c4c8fd0a-5928-4240-9849-f829dd0b4379.png)

L'état d'ouverture du volet pouvait être associé à la commande action setclosure il fut un temps. Mais elle a soudain disparu... à mon grand regret.

PS : pour exemple un module shelly qui permet toujours d'associer un des états de son choix du module, à la commande action :  

![image](https://user-images.githubusercontent.com/56517380/155033585-7d93b1e1-1d20-404c-9d91-440d8c12a711.png)

**Comment by Alderaaan** [comment]
Idem, je confirme que rien n'a changé de mon côté.

**Comment by antarmc** [comment]
Un retour suite a nos constats de non correction ???
