### ISSUE TITLE
Too many operations

### ISSUE THREAD

**Issue by seunlands** [redbug26/jeedom-tahoma#37]
Bonjour,

Depuis maintenant au moins une semaine, les commandes de fermeture de volet à partir d'un scénario ne fonctionne plus.
J'ai un message Too many operations

Pouvez-vous voir ce qu"il se passe ?

Merci

**Comment by redbug26** [comment]
Cela arrive lorsque le pooling est trop fréquent. Limitation de l'API de Jeedom :(
