### ISSUE TITLE
Plugin Hs sur Jeedom 4.1.20

### ISSUE THREAD

**Issue by Angelbox60** [redbug26/jeedom-tahoma#38]
Aprés avoir vu que mes scenarios ne fonctionnent plus je me suis tourné vers le plugin.
Il ne reconnait plus mon ID
Réinstallation faite et ça ne fonctionne toujours pas.
Message : Invalid returnInvalid return{"state":"ok","result":""}

**Comment by dummyno** [comment]
Dear Redbug

I am facing the same problem after having used your plug in for years now with great pleasure.
The case :
My tahoma broke. I had to replace it by a new one.

I have had the yellow guys from somfy replicating my old config onto the new tahoma box.

Login password entered correctly, but having the same issue as Angelbox60

PI deleted - Jeedom reboot - PI reinstalles no effect

While all devices are lost, clicking on Sync ends up with error message :

**Invalid returnInvalid returnInvalid return{"state":"ok","result":""}**

Password is OK
Works fine linking GoogleHome and Somfy API

Any hint for us ?

Thanks a lot for your help


PS : my system is yours for investigating

**Comment by dummyno** [comment]
**SOLUTION FOUND**
It is a mix of patience trust and faith LOL

It appeared despite the message few minutes later when I returned onto the plug in device list

All is perfect thanks redbug

**Comment by redbug26** [comment]
Weird but Ok ;) I close the problem.
Don't hesitate to go back If the problem still appears ;) (and you could join us on discord oto)
