### ISSUE TITLE
Les commandes disparaissent après une sauvegarde 

### ISSUE THREAD

**Issue by Merrick28** [redbug26/jeedom-tahoma#57]
Bonjour 

(reprise du fil initial situé ici : https://community.jeedom.com/t/les-commandes-disparaissent-apres-une-sauvegarde/101121)

J’utilise le plugin Tahoma depuis quelques semaines, en conjonction avec InfluxDB pour avoir des graphes.
Depuis deux jours (environ), j’ai un élément de Tahoma dont les commandes sont « vides » de configuration. Il s’agit d’un module fil pilote pour radiateur électrique. Sur mes 4 équipements, 3 sont corrects, et l’un n’a pas les bonnes infos, notamment pour la commande « core:TargetHeatingLevelState »

Petits compléments : l’équipement peut être piloté par jeedom et par la tahoma (je peux changer la cible du chauffage sans souci).
Quand je renomme dans la tahoma, que je supprime l’élément dans jeedom et que je resynchro, je le vois bien apparaître avec le bon nom, et les bonnes commandes…

Je pense avoir ciblé la source du problème : les commandes « sautent » dès que je rattache l’équipement à une pièce, quelle qu’elle soit, ou bien qu'on fait une modification puis une sauvegarde de la commande.

Problème constaté sur la stable et la beta.

**Comment by MADomotique** [comment]
Hello, 
Sur ma Beta, j'ai corrigé le problème en remettant l'ancienne ligne 71 du fichier [desktop/js/tahoma.js](https://github.com/redbug26/jeedom-tahoma/commit/f3f228bc537dccf90b0785f81fd564d01ebebb16#diff-e776ee09c0a346126ff037adf48be3d66e447cb7c7034a187d1ac96f37e3f3f2)
<img width="668" alt="image" src="https://user-images.githubusercontent.com/78885669/217276288-58276269-d293-467c-9194-1ee421dd268c.png">

A valider par RedBug
<img width="716" alt="image" src="https://user-images.githubusercontent.com/78885669/217276063-060973ed-8a1a-4d66-bb16-f7c90408eae9.png">

**Comment by antarmc** [comment]
salut messieurs, 

oui .... si redbug daigne considérer ses clients de ce plugin, car moi il me mets des vents depuis des mois sur la disparition de la commande info de la position de mes volets, malgré issue ouverte et multiples relances !

**Comment by redbug26** [comment]
J'ai remis la version précedente (merci a @MADomotique)
@antarmc Je ne te nie pas.. et ne vous considère pas comme des clients, juste des utilisateurs. Le plugin est open-source et peut être installé gratuitement. 
@Mips2648 Tu sais regarder pourquoi ta modif supprimait les commandes ? Je ne vois pas la raison.
